crunch/django/app/urls.py
from django.urls import include, path
from django.urls import reverse_lazy
from django.views.generic import RedirectView
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'projects', views.ProjectAPI)
router.register(r'datasets', views.DatasetAPI)
router.register(r'items', views.ItemAPI)
router.register(r'attributes/char', views.CharAttributeAPI)
router.register(r'attributes/float', views.FloatAttributeAPI)
router.register(r'attributes/int', views.IntegerAttributeAPI)
router.register(r'attributes/filesize', views.FilesizeAttributeAPI)
router.register(r'attributes/bool', views.BooleanAttributeAPI)
router.register(r'attributes/url', views.URLAttributeAPI)
router.register(r'attributes/lat-long', views.LatLongAttributeAPI)
router.register(r'attributes/datetime', views.DateTimeAttributeAPI)
router.register(r'attributes/date', views.DateAttributeAPI)

app_name = "crunch"
urlpatterns = [
    path('', views.ProjectListView.as_view(), name='project-list'),
    path('api/', include( (router.urls, 'api') )),
    path('api/statuses/', views.StatusListCreateAPIView.as_view(), name='status-list'),
    path('api/next/', views.NextDatasetReference.as_view(), name='next'),

    path('projects/', RedirectView.as_view(url="..", permanent=False)),
    path("projects/create/", views.ProjectCreateView.as_view(), name="project-create"),
    path('projects/<str:slug>/', views.ProjectDetailView.as_view(), name='project-detail'),
    path("projects/<str:slug>/update/", views.ProjectUpdateView.as_view(), name="project-update"),
    path("api/projects/<str:slug>/next/", views.ProjectNextDatasetReference.as_view(), name="project-api-next"),
    
    path("datasets/create/", views.DatasetCreateView.as_view(), name="dataset-create"),
    path('projects/<str:project>/datasets/', RedirectView.as_view(url="..", permanent=False)),
    path('projects/<str:project>/datasets/<str:slug>', views.DatasetDetailView.as_view(), name='dataset-detail'),
    path("projects/<str:project>/datasets/<str:slug>/update/", views.DatasetUpdateView.as_view(), name="dataset-update"),

    path("items/create/", views.ItemCreateView.as_view(), name="item-create"),
    path('items/<str:slug>/', views.ItemDetailView.as_view(), name='item-detail'),
    path('items/<str:slug>/map/', views.ItemMapView.as_view(), name='item-map'),
    path('items/<str:slug>/update/', views.ItemUpdateView.as_view(), name='item-update'),
]

crunch/django/proj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crunch.django.app.urls')),
    path('', include('cms.urls')),
]

crunch/templates/crunch/dataset_detail.html
{% extends "base.html" %}
{% load crunch %}

{% block content %}

<div class="container mt-3">

    <nav aria-label="breadcrumb ">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="../..">Projects</a></li>
            <li class="breadcrumb-item"><a href="..">{{dataset.parent}}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{dataset}}</li>
        </ol>
    </nav>

    <div class="float-right">
        {% if perms.crunch.add_dataset %}
            <a href="{% url 'crunch:dataset-create'  %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Create Dataset">
                <i class="fas fa-plus"></i>
            </a>
        {% endif %}
        {% if perms.crunch.update_dataset %}
            <a href="{% url 'crunch:dataset-update' slug=dataset.slug project=dataset.parent.slug %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Update this Dataset">
                <i class="fas fa-edit"></i>
            </a>
        {% endif %}
        <a href="{% url 'crunch:api:dataset-detail' slug=dataset.slug %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="JSON">
          <i class="fas fa-code"></i>
        </a>
        {% if request.user.is_staff %}
            <a href="{{ dataset.get_admin_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Admin">
                <i class="fas fa-tools"></i>
            </a>
        {% endif %}
        {% if dataset.prev_in_order %}
            <a href="{{ dataset.prev_in_order.get_absolute_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="{{ dataset.prev_in_order }}">
                <i class="fas fa-arrow-left"></i>
            </a>
        {% endif %}
        {% if dataset.next_in_order %}
            <a href="{{ dataset.next_in_order.get_absolute_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="{{ dataset.next_in_order }}">
                <i class="fas fa-arrow-right"></i>
            </a>
        {% endif %}
        <a href="{{ dataset.get_admin_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="{% if not dataset.locked %}Unlocked{%else%}Locked{% endif %}">
          <i class="fas fa-{% if not dataset.locked %}un{% endif %}lock"></i>
        </a>

    </div> 

    <h2>{{dataset}}</h2>

    <h3>Project: <a href='{{dataset.parent.get_absolute_url}}'>{{dataset.parent}}</a></h3>
    <p class="font-weight-bold">{{dataset.description}}</p>
    <p>{{dataset.details}}</p>

    <hr>
    <div class="float-right">
        {% if request.user.is_staff %}
            <a href="{% url 'admin:crunch_attribute_add'  %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Create Attribute">
                <i class="fas fa-plus"></i>
            </a>
        {% endif %}
    </div>

    <h3>{{dataset.children.count}} Items</h3>
    <ul>
    {% for item in dataset.children.all %}
        <li>
            <a href='{{item.get_absolute_url}}' 
            {% if item.description %}
                data-toggle="tooltip" data-placement="bottom" title="{{item.description}}"
            {% endif %}
            >
                {{item}}
            </a>
        </li>
    {% endfor %}
    </ul>

    {% if dataset.attributes.count %}
    <h3>Attributes</h3>

    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Attribute</th>
            <th scope="col">Type</th>
            <th scope="col">Value</th>
            {% if request.user.is_staff %}
            <th scope="col">Admin</th>
            {% endif %}        
          </tr>
        </thead>
        <tbody>
            {% for attribute in dataset.attributes.all %}
            <tr>
                <th scope="row">{{attribute.key}}</th>
                <td>{{attribute.type_str}}</td>
                <td>{{attribute.value_html}}</td>
                {% if request.user.is_staff %}
                <td>
                    <a href="{{ attribute.get_admin_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Edit Attribute">
                        <i class="fas fa-tools"></i>
                    </a>
                </td>
                {% endif %}        

            </tr>
            {% endfor %}
            <tr>
                <th scope="row">Total Filesize</th>
                <td>Filesize</td>
                <td>{{ dataset.descendant_total_filesize_readable }}</td>
                {% if request.user.is_staff %}
                <td>
                </td>
                {% endif %}        
            </tr>
        </tbody>
      </table>
      <hr>


      
      {% endif %}
      {% item_map dataset %}


      <div class="float-right">
          {% if request.user.is_staff %}
              <a href="#" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Upload File">
                  <i class="fas fa-plus"></i>
              </a>
          {% endif %}
      </div>  

      <h3>Files</h3>
      {{ dataset.files_html|safe }}

    <hr>

    {% if dataset.statuses.count %}
    <h3>History</h3>
    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Date</th>
            <th scope="col">User</th>
            <th scope="col">Stage</th>
            <th scope="col">Status</th>
            {% if request.user.is_staff %}
            <th scope="col">Admin</th>
            {% endif %}        
          </tr>
        </thead>
        <tbody>
            {% for status in dataset.statuses.all %}
            <tr>
                <th scope="row">{{status.created}}</th>
                <td>{{status.site_user}}</td>
                <td>{{status.get_stage_display}}</td>
                <td>{{status.get_state_display}}</td>
                {% if request.user.is_staff %}
                <td>
                    <a href="{{ status.get_admin_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Edit Status">
                        <i class="fas fa-tools"></i>
                    </a>
                </td>
                {% endif %}        
              </tr>
            {% endfor %}
        </tbody>
      </table>
      {% endif %}
  
</div>

{% endblock content %}

crunch/templates/crunch/dataset_list.html
<ul>
  <p>{{datasets.count}} Datasets</p>
  {% for dataset in datasets.all %}
    <li>
      <a href='{{dataset.get_absolute_url}}' 
      {% if dataset.description %}
          data-toggle="tooltip" data-placement="bottom" title="{{dataset.description}}"
      {% endif %}
      >
          {{dataset}}
      </a>
    </li>
  {% endfor %}
</ul>

crunch/templates/crunch/item_detail.html
{% extends "base.html" %}
{% load crunch %}

{% block content %}

<div class="container mt-3">


    <div class="float-right">
        {% if perms.crunch.add_dataset %}
            <a href="{% url 'crunch:item-create'  %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Create item">
                <i class="fas fa-plus"></i>
            </a>
        {% endif %}
        {% if perms.crunch.update_item %}
            <a href="{% url 'crunch:item-update' slug=item.slug %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Update this item">
                <i class="fas fa-edit"></i>
            </a>
        {% endif %}
        {% if request.user.is_staff %}
            <a href="{{ item.get_admin_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Admin">
                <i class="fas fa-tools"></i>
            </a>
        {% endif %}
        {% if item.prev_in_order %}
            <a href="{{ item.prev_in_order.get_absolute_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="{{ item.prev_in_order }}">
                <i class="fas fa-arrow-left"></i>
            </a>
        {% endif %}
        {% if item.next_in_order %}
            <a href="{{ item.next_in_order.get_absolute_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="{{ item.next_in_order }}">
                <i class="fas fa-arrow-right"></i>
            </a>
        {% endif %}
    </div> 

    <h2>{{item}}</h2>

    <h3>Parent: <a href='{{item.parent.get_absolute_url}}'>{{item.parent}}</a></h3>
    <p class="font-weight-bold">{{item.description}}</p>
    <p>{{item.details}}</p>

    <hr>
    <div class="float-right">
        {% if request.user.is_staff %}
            <a href="{% url 'admin:crunch_attribute_add'  %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Create Attribute">
                <i class="fas fa-plus"></i>
            </a>
        {% endif %}
    </div>

    {% if item.children.count %}
    <h3>{{item.children.count}} Children</h3>
    <ul>
    {% for i in i.children.all %}
        <li>
            <a href='{{i.get_absolute_url}}' 
            {% if i.description %}
                data-toggle="tooltip" data-placement="bottom" title="{{i.description}}"
            {% endif %}
            >
                {{i}}
            </a>
        </li>
    {% endfor %}
    </ul>
    {% endif %}

    <h3>Attributes</h3>

    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Attribute</th>
            <th scope="col">Type</th>
            <th scope="col">Value</th>
            {% if request.user.is_staff %}
            <th scope="col">Admin</th>
            {% endif %}        
          </tr>
        </thead>
        <tbody>
            {% for attribute in item.attributes.all %}
            <tr>
                <th scope="row">{{attribute.key}}</th>
                <td>{{attribute.type_str}}</td>
                <td>{{attribute.value_html}}</td>
                {% if request.user.is_staff %}
                <td>
                    <a href="{{ attribute.get_admin_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Edit Attribute">
                        <i class="fas fa-tools"></i>
                    </a>
                </td>
                {% endif %}        

              </tr>
            {% endfor %}
        </tbody>
      </table>
      

      <hr>
      <div class="float-right">
          {% if request.user.is_staff %}
              <a href="#" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Upload File">
                  <i class="fas fa-plus"></i>
              </a>
          {% endif %}
      </div>  

      {% item_map dataset %}
  
</div>

{% endblock content %}

crunch/templates/crunch/item_map.html
{% if item.has_descendant_latlongattributes %}
    <h2>Map</h2>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="{% url 'crunch:item-map' slug=item.slug %}" allowfullscreen></iframe>
    </div>        
{% endif %}

crunch/templates/crunch/project_detail.html
{% extends "base.html" %}
{% load crunch %}

{% block content %}

<div class="container mt-3">

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="..">Projects</a></li>
          <li class="breadcrumb-item active" aria-current="page">{{project}}</li>
        </ol>
    </nav>
      
    <div class="float-right">
        {% if perms.crunch.add_project %}
            <a href="{% url 'crunch:project-create'  %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Create Project">
                <i class="fas fa-plus"></i>
            </a>
        {% endif %}
        {% if perms.crunch.update_project %}
            <a href="{% url 'crunch:project-update' slug=project.slug %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Update this Project">
                <i class="fas fa-edit"></i>
            </a>
        {% endif %}
        <a href="{% url 'crunch:api:project-detail' slug=project.slug %}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="JSON">
          <i class="fas fa-code"></i>
        </a>  
        {% if request.user.is_staff %}
            <a href="{{ project.get_admin_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Admin">
                <i class="fas fa-tools"></i>
            </a>
        {% endif %}
        {% if project.prev_in_order %}
            <a href="{{ project.prev_in_order.get_absolute_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="{{ project.prev_in_order }}">
                <i class="fas fa-arrow-left"></i>
            </a>
        {% endif %}
        {% if project.next_in_order %}
            <a href="{{ project.next_in_order.get_absolute_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="{{ project.next_in_order }}">
                <i class="fas fa-arrow-right"></i>
            </a>
        {% endif %}
    </div> 


    <h2>{{project}}</h2>

    <p class="font-weight-bold">{{project.description}}</p>
    <p>{{project.details}}</p>

    <h3>Unprocessed Datasets</h3>
    {% dataset_list project.unprocessed_datasets %}

    <h3>Running Datasets</h3>
    {% dataset_list project.running_datasets %}

    <h3>Completed Datasets</h3>
    {% dataset_list project.completed_datasets %}

    <h3>Failed Datasets</h3>
    {% dataset_list project.failed_datasets %}

    <h3>Attributes</h3>

    <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Attribute</th>
            <th scope="col">Type</th>
            <th scope="col">Value</th>
            {% if request.user.is_staff %}
            <th scope="col">Admin</th>
            {% endif %}        
          </tr>
        </thead>
        <tbody>
            {% for attribute in project.attributes.all %}
            <tr>
                <th scope="row">{{attribute.key}}</th>
                <td>{{attribute.type_str}}</td>
                <td>{{attribute.value_html}}</td>
                {% if request.user.is_staff %}
                <td>
                    <a href="{{ attribute.get_admin_url }}" class="btn btn-outline-primary btn-sm chk-saved" data-toggle="tooltip" data-placement="bottom" title="Edit Attribute">
                        <i class="fas fa-tools"></i>
                    </a>
                </td>
                {% endif %}        

            </tr>
            {% endfor %}
            <tr>
                <th scope="row">Total Filesize</th>
                <td>Filesize</td>
                <td>{{ project.descendant_total_filesize_readable }}</td>
                {% if request.user.is_staff %}
                <td>
                </td>
                {% endif %}        
            </tr>
        </tbody>
      </table>    
      
      {% item_map project %}

</div>

{% endblock content %}

crunch/templates/crunch/project_list.html
{% extends "base.html" %}

{% block content %}
  
  <div class="container mt-3">
  <h2>Project List</h2>

    <div class="row">
        {% for project in page_obj %}
          <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                  <span class="badge badge-pill badge-primary">Project</span>
                  <a href='{{project.get_absolute_url}}'><h3 class="card-title">{{project}}</h3></a>
                  <p class="card-text">{{ project.description }}</p>
                  <p>{{project.children.count}} dataset(s).</p>
                  <a href='{{project.get_absolute_url}}' class="btn btn-primary">View Project</a>
                </div>
            </div>
          </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}